python ./code/train_mammary.py --dataset 1189 --train_dataset train_dataset2 --test_dataset test_dataset2 \
--tissue small_intestine --gpu 1 \
--dense_dim 400 \
--hidden_dim 200 \
--lr 1e-5 \
--n_epochs 1000 \
--batch_size 320 \
--dropout 0.0 \
--loss_weight 1 \
--n_layers 1 \
--pretrained_model_path checkpoints/best_modelv2.pth \
--load_pretrained_model 0 \
--save_model_path checkpoints/best_modelv2.pth \
--just_train 1 \
--each_dataset_size 100
