python ./code/train_mammary.py --dataset 1189 --train_dataset train_dataset2 --test_dataset test_dataset2 \
--tissue small_intestine --gpu 1 \
--dense_dim 150 \
--hidden_dim 40 \
--lr 1e-3 \
--n_epochs 300 \
--batch_size 256 \
--dropout 0.1 \
--loss_weight 10 1 \
--n_layers 3 \
--pretrained_model_path checkpoints/best_modelv2.pth \
--load_pretrained_model 0 \
--save_model_path checkpoints/best_modelv2.pth \
--just_train 0 \
--using_mmd 0 \
--each_dataset_size 500
