python ./codes/train_mammary_bone_marrow.py --data_dir mouse_bone_marrow \
--cell_data_path mouse_bone_marrow_911_data.csv \
--ligand_receptor_gene mouse_ligand_receptor_pair.csv \
--train_dataset train_dataset \
--test_dataset test_dataset \
--gpu 0 \
--dense_dim 80 \
--hidden_dim 40 \
--lr 1e-4 \
--n_epochs 100 \
--batch_size 32 \
--dropout 0.1 \
--loss_weight 1 1 \
--n_layers 2 \
--pretrained_model_path checkpoints/best_modelv5.pth \
--load_pretrained_model 0 \
--save_model_path checkpoints/best_modelv5.pth \
--score_limit 20